# Series
A Series is a one-dimensional object similar to an array, list, or column in a table. It will assign a labeled index to each item in the Series. By default, each item will receive an index label from 0 to N, where N is the length of the Series minus one.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('max_columns', 50)
%matplotlib inline

# create a Series with an arbitrary list
s = pd.Series([7, 'Heisenberg', 3.14, -1789710578, 'Happy Eating!'])
s

0                7
1       Heisenberg
2             3.14
3      -1789710578
4    Happy Eating!
dtype: object

Alternatively, you can specify an index to use when creating the Series.

In [2]:
s = pd.Series([7, 'Heisenberg', 3.14, -1789710578, 'Happy Eating!'],
              index=['A', 'Z', 'C', 'Y', 'E'])
s

A                7
Z       Heisenberg
C             3.14
Y      -1789710578
E    Happy Eating!
dtype: object

The Series constructor can convert a dictonary as well, using the keys of the dictionary as its index.



In [3]:
d = {'Chicago': 1000, 'New York': 1300, 'Portland': 900, 'San Francisco': 1100,
     'Austin': 450, 'Boston': None}
cities = pd.Series(d)
cities

Austin            450.0
Boston              NaN
Chicago          1000.0
New York         1300.0
Portland          900.0
San Francisco    1100.0
dtype: float64

In [4]:
cities[['Chicago', 'Portland', 'San Francisco']]


Chicago          1000.0
Portland          900.0
San Francisco    1100.0
dtype: float64

In [5]:
cities[cities < 1000]


Austin      450.0
Portland    900.0
dtype: float64

`cities < 1000` returns a Series of True/False values, which we then pass to our Series cities, returning the corresponding True items.

In [6]:
# changing values using boolean logic
cities[cities < 1000] = 750

cities[cities < 1000]

Austin      750.0
Portland    750.0
dtype: float64

In [7]:
print('Seattle' in cities)
print('San Francisco' in cities)

False
True


Mathematical operations can be done using scalars and functions.


In [8]:
# divide city values by 3
cities / 3


Austin           250.000000
Boston                  NaN
Chicago          333.333333
New York         433.333333
Portland         250.000000
San Francisco    366.666667
dtype: float64

In [9]:
# square city values
np.square(cities)

Austin            562500.0
Boston                 NaN
Chicago          1000000.0
New York         1690000.0
Portland          562500.0
San Francisco    1210000.0
dtype: float64

In [10]:
print(cities[['Chicago', 'New York', 'Portland']])
print('\n')
print(cities[['Austin', 'New York']])
print('\n')
print(cities[['Chicago', 'New York', 'Portland']] + cities[['Austin', 'New York']])

Chicago     1000.0
New York    1300.0
Portland     750.0
dtype: float64


Austin       750.0
New York    1300.0
dtype: float64


Austin         NaN
Chicago        NaN
New York    2600.0
Portland       NaN
dtype: float64


In [11]:
# returns a boolean series indicating which values aren't NULL
print(cities.notnull())
print('\n')
print(cities.isnull())


Austin            True
Boston           False
Chicago           True
New York          True
Portland          True
San Francisco     True
dtype: bool


Austin           False
Boston            True
Chicago          False
New York         False
Portland         False
San Francisco    False
dtype: bool


# DataFrames

Using the columns parameter allows us to tell the constructor how we'd like the columns ordered. By default, the DataFrame constructor will order the columns alphabetically (though this isn't the case when reading from a file - more on that next).

In [12]:
data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
        'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions', 'Lions', 'Lions'],
        'wins': [11, 8, 10, 15, 11, 6, 10, 4],
        'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
football = pd.DataFrame(data, columns=['year', 'team', 'wins', 'losses'])
football

year     team  wins  losses
0  2010    Bears    11       5
1  2011    Bears     8       8
2  2012    Bears    10       6
3  2011  Packers    15       1
4  2012  Packers    11       5
5  2010    Lions     6      10
6  2011    Lions    10       6
7  2012    Lions     4      12

Reading a CSV is as simple as calling the read_csv function. By default, the read_csv function expects the column separator to be a comma, but you can change that using the sep parameter.



In [13]:
from_csv = pd.read_csv('olive.csv')
from_csv.head()

Unnamed: 0  region  area  palmitic  palmitoleic  stearic  oleic  \
0  1.North-Apulia       1     1      1075           75      226   7823   
1  2.North-Apulia       1     1      1088           73      224   7709   
2  3.North-Apulia       1     1       911           54      246   8113   
3  4.North-Apulia       1     1       966           57      240   7952   
4  5.North-Apulia       1     1      1051           67      259   7771   

   linoleic  linolenic  arachidic  eicosenoic  
0       672         36         60          29  
1       781         31         61          29  
2       549         31         63          29  
3       619         50         78          35  
4       672         50         80          46

Our file had headers, which the function inferred upon reading in the file. Had we wanted to be more explicit, we could have passed header=None to the function along with a list of column names to use:



In [14]:
cols = ['num', 'game', 'date', 'team', 'home_away', 'opponent',
        'result', 'quarter', 'distance', 'receiver', 'score_before',
        'score_after']
no_headers = pd.read_csv('peyton-passing-TDs-2012.csv', sep=',', header=None,
                          names=cols)

FileNotFoundError: File b'peyton-passing-TDs-2012.csv' does not exist

There's also a set of writer functions for writing to a variety of formats (CSVs, HTML tables, JSON). They function exactly as you'd expect and are typically called to_format:

`my_dataframe.to_csv('path_to_file.csv')`

### Reading Excel files
Reading Excel files requires the xlrd library. You can install it via pip (`pip install xlrd`).

In [ ]:
football.to_excel('football.xlsx', index=False)

In [15]:
# delete the DataFrame
del football

# read from Excel
football = pd.read_excel('football.xlsx', 'Sheet1')
football

year     team  wins  losses
0  2010    Bears    11       5
1  2011    Bears     8       8
2  2012    Bears    10       6
3  2011  Packers    15       1
4  2012  Packers    11       5
5  2010    Lions     6      10
6  2011    Lions    10       6
7  2012    Lions     4      12

In [36]:
from pandas.io import sql
import sqlite3

conn = sqlite3.connect('')
query = "SELECT * FROM towed WHERE make = 'FORD';"

results = sql.read_sql(query, con=conn)
results.head()

DatabaseError: Execution failed on sql 'SELECT * FROM towed WHERE make = 'FORD';': no such table: towed

### Reading URLs
With read_table, we can also read directly from a URL.

In [ ]:
url = 'https://raw.github.com/gjreda/best-sandwiches/master/data/best-sandwiches-geocode.tsv'

# fetch the text from the URL and read it into a DataFrame
from_url = pd.read_table(url, sep='\t')
from_url.head(3)

### Google Analytics

pandas also has some integration with the Google Analytics API, though there is some setup required. I won't be covering it, but you can read more about it [here](http://blog.yhathq.com/posts/pandas-google-analytics.html) and [here](http://quantabee.wordpress.com/2012/12/17/google-analytics-pandas/).



In [17]:
u_cols = ['Area', 'Region', 'Area', 'Palmitic','Palmitoleic','Stearic','Oleic','Linoleic','Linolenic','Arachidic','Eicosenoic']
olive = pd.read_csv('olive.csv', header=0, names=u_cols)
olive.head(10)
olive[0:10] # Same thing

Area  Region  Area.1  Palmitic  Palmitoleic  Stearic  Oleic  \
0   1.North-Apulia       1       1      1075           75      226   7823   
1   2.North-Apulia       1       1      1088           73      224   7709   
2   3.North-Apulia       1       1       911           54      246   8113   
3   4.North-Apulia       1       1       966           57      240   7952   
4   5.North-Apulia       1       1      1051           67      259   7771   
5   6.North-Apulia       1       1       911           49      268   7924   
6   7.North-Apulia       1       1       922           66      264   7990   
7   8.North-Apulia       1       1      1100           61      235   7728   
8   9.North-Apulia       1       1      1082           60      239   7745   
9  10.North-Apulia       1       1      1037           55      213   7944   

   Linoleic  Linolenic  Arachidic  Eicosenoic  
0       672         36         60          29  
1       781         31         61          29  
2       549         31         63          29  
3       619         50         78          35  
4       672         50         80          46  
5       678         51         70          44  
6       618         49         56          29  
7       734         39         64          35  
8       709         46         83          33  
9       633         26         52          30

In [31]:
olive.dtypes
olive.info()
olive.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 572 entries, 0 to 571
Data columns (total 11 columns):
Area           572 non-null object
Region         572 non-null int64
Area.1         572 non-null int64
Palmitic       572 non-null int64
Palmitoleic    572 non-null int64
Stearic        572 non-null int64
Oleic          572 non-null int64
Linoleic       572 non-null int64
Linolenic      572 non-null int64
Arachidic      572 non-null int64
Eicosenoic     572 non-null int64
dtypes: int64(10), object(1)
memory usage: 49.2+ KB


(572, 11)

In [33]:
olive.shape

(572, 11)

In [37]:
olive['Area']

0        1.North-Apulia
1        2.North-Apulia
2        3.North-Apulia
3        4.North-Apulia
4        5.North-Apulia
5        6.North-Apulia
6        7.North-Apulia
7        8.North-Apulia
8        9.North-Apulia
9       10.North-Apulia
10      11.North-Apulia
11      12.North-Apulia
12      13.North-Apulia
13      14.North-Apulia
14      15.North-Apulia
15      16.North-Apulia
16      17.North-Apulia
17      18.North-Apulia
18      19.North-Apulia
19      20.North-Apulia
20      21.North-Apulia
21      22.North-Apulia
22      23.North-Apulia
23      24.North-Apulia
24      25.North-Apulia
25          26.Calabria
26          27.Calabria
27          28.Calabria
28          29.Calabria
29          30.Calabria
             ...       
542    543.West-Liguria
543    544.West-Liguria
544    545.West-Liguria
545    546.West-Liguria
546    547.West-Liguria
547    548.West-Liguria
548    549.West-Liguria
549    550.West-Liguria
550    551.West-Liguria
551    552.West-Liguria
552    553.West-

In [19]:
olive[['Region', 'Stearic']][(olive['Stearic'] < 220) | (olive['Region'] > 1)].head(3)

Region  Stearic
9        1      213
10       1      219
12       1      214

In [20]:
olive_with_index = olive.set_index('Area')
olive_with_index.head()
olive_with_index.tail()

# users.set_index('user_id', inplace=True)

Region  Area.1  Palmitic  Palmitoleic  Stearic  Oleic  \
Area                                                                      
568.West-Liguria       3       8      1280          110      290   7490   
569.West-Liguria       3       8      1060          100      270   7740   
570.West-Liguria       3       8      1010           90      210   7720   
571.West-Liguria       3       8       990          120      250   7750   
572.West-Liguria       3       8       960           80      240   7950   

                  Linoleic  Linolenic  Arachidic  Eicosenoic  
Area                                                          
568.West-Liguria       790         10         10           2  
569.West-Liguria       810         10         10           3  
570.West-Liguria       970          0          0           2  
571.West-Liguria       870         10         10           2  
572.West-Liguria       740         10         20           2

We can select rows by position using the iloc method.

In [21]:
print(olive_with_index.iloc[99])
print('\n\n')
print(olive_with_index.iloc[[3,58,105]])

Region            1
Area.1            3
Palmitic       1286
Palmitoleic     163
Stearic         183
Oleic          7040
Linoleic       1230
Linolenic        29
Arachidic        57
Eicosenoic       12
Name: 100.South-Apulia, dtype: int64



                  Region  Area.1  Palmitic  Palmitoleic  Stearic  Oleic  \
Area                                                                      
4.North-Apulia         1       1       966           57      240   7952   
59.Calabria            1       2      1198          136      239   7639   
106.South-Apulia       1       3      1387          182      242   6913   

                  Linoleic  Linolenic  Arachidic  Eicosenoic  
Area                                                          
4.North-Apulia         619         50         78          35  
59.Calabria            633         27         55          19  
106.South-Apulia      1101         44         68          30  


And we can select rows by label with the loc method.



In [22]:
print(olive_with_index.loc['4.North-Apulia'])
print('\n\n')
print(olive_with_index.loc[['5.North-Apulia	','571.West-Liguria']])

Region            1
Area.1            1
Palmitic        966
Palmitoleic      57
Stearic         240
Oleic          7952
Linoleic        619
Linolenic        50
Arachidic        78
Eicosenoic       35
Name: 4.North-Apulia, dtype: int64



                  Region  Area.1  Palmitic  Palmitoleic  Stearic   Oleic  \
Area                                                                       
5.North-Apulia\t     NaN     NaN       NaN          NaN      NaN     NaN   
571.West-Liguria     3.0     8.0     990.0        120.0    250.0  7750.0   

                  Linoleic  Linolenic  Arachidic  Eicosenoic  
Area                                                          
5.North-Apulia\t       NaN        NaN        NaN         NaN  
571.West-Liguria     870.0       10.0       10.0         2.0  


If we realize later that we liked the old pandas default index, we can just reset_index. The same rules for inplace apply.



In [23]:
olive_with_index.reset_index(inplace=True)
olive_with_index

Area  Region  Area.1  Palmitic  Palmitoleic  Stearic  Oleic  \
0      1.North-Apulia       1       1      1075           75      226   7823   
1      2.North-Apulia       1       1      1088           73      224   7709   
2      3.North-Apulia       1       1       911           54      246   8113   
3      4.North-Apulia       1       1       966           57      240   7952   
4      5.North-Apulia       1       1      1051           67      259   7771   
5      6.North-Apulia       1       1       911           49      268   7924   
6      7.North-Apulia       1       1       922           66      264   7990   
7      8.North-Apulia       1       1      1100           61      235   7728   
8      9.North-Apulia       1       1      1082           60      239   7745   
9     10.North-Apulia       1       1      1037           55      213   7944   
10    11.North-Apulia       1       1      1051           35      219   7978   
11    12.North-Apulia       1       1      1036           59      235   7868   
12    13.North-Apulia       1       1      1074           70      214   7728   
13    14.North-Apulia       1       1       875           52      243   8018   
14    15.North-Apulia       1       1       952           49      254   7795   
15    16.North-Apulia       1       1      1155           98      201   7606   
16    17.North-Apulia       1       1       943           94      183   7840   
17    18.North-Apulia       1       1      1278           69      205   7344   
18    19.North-Apulia       1       1       961           70      195   7958   
19    20.North-Apulia       1       1       952           77      258   7820   
20    21.North-Apulia       1       1      1074           67      236   7692   
21    22.North-Apulia       1       1       995           46      288   7806   
22    23.North-Apulia       1       1      1056           53      247   7703   
23    24.North-Apulia       1       1      1065           39      234   7876   
24    25.North-Apulia       1       1      1065           45      245   7779   
25        26.Calabria       1       2      1315          139      230   7299   
26        27.Calabria       1       2      1321          136      217   7174   
27        28.Calabria       1       2      1359          115      246   7234   
28        29.Calabria       1       2      1378          111      272   7127   
29        30.Calabria       1       2      1295          109      245   7253   
..                ...     ...     ...       ...          ...      ...    ...   
542  543.West-Liguria       3       8      1020          100      290   7620   
543  544.West-Liguria       3       8       970           90      220   7700   
544  545.West-Liguria       3       8      1180          130      220   7450   
545  546.West-Liguria       3       8      1060          140      240   7690   
546  547.West-Liguria       3       8       990          100      250   7630   
547  548.West-Liguria       3       8      1010           90      350   7630   
548  549.West-Liguria       3       8      1040           90      250   7780   
549  550.West-Liguria       3       8      1040           90      250   7810   
550  551.West-Liguria       3       8      1020           90      350   7620   
551  552.West-Liguria       3       8      1020           90      260   7620   
552  553.West-Liguria       3       8      1010           90      350   7610   
553  554.West-Liguria       3       8       920          110      340   7720   
554  555.West-Liguria       3       8      1030          100      250   7710   
555  556.West-Liguria       3       8       960           90      300   7820   
556  557.West-Liguria       3       8      1030          110      210   7810   
557  558.West-Liguria       3       8      1010          100      240   7710   
558  559.West-Liguria       3       8      1020           90      240   7800   
559  560.West-Liguria       3       8      1120           90      300   7650   
560  561.West-Lig

I've found that I can usually get by with boolean indexing, loc and iloc, but pandas has a whole host of other ways to do selection.

#### Joining

Like SQL's JOIN clause, pandas.merge allows two DataFrames to be joined on one or more keys. The function provides a series of parameters (on, left_on, right_on, left_index, right_index) allowing you to specify the columns or indexes on which to join.

In [24]:
left_frame = pd.DataFrame({'key': range(5), 
                           'left_value': ['a', 'b', 'c', 'd', 'e']})
right_frame = pd.DataFrame({'key': range(2, 7), 
                           'right_value': ['f', 'g', 'h', 'i', 'j']})
print(left_frame)
print('\n')
print(right_frame)

   key left_value
0    0          a
1    1          b
2    2          c
3    3          d
4    4          e


   key right_value
0    2           f
1    3           g
2    4           h
3    5           i
4    6           j


In [25]:
pd.merge(left_frame, right_frame, on='key', how='inner')

key left_value right_value
0    2          c           f
1    3          d           g
2    4          e           h

Alternatively, if our keys were indexes, we could use the left_index or right_index parameters, which accept a True/False value. You can mix and match columns and indexes like so:



In [26]:
pd.merge(left_frame, right_frame, left_on='key', right_index=True)

key  key_x left_value  key_y right_value
0    0      0          a      2           f
1    1      1          b      3           g
2    2      2          c      4           h
3    3      3          d      5           i
4    4      4          e      6           j

In [27]:
pd.merge(left_frame, right_frame, right_on='key', left_index=True)

key  key_x left_value  key_y right_value
0    2      2          c      2           f
1    3      3          d      3           g
2    4      4          e      4           h

In [28]:
pd.merge(left_frame, right_frame, on='key', how='right')

key left_value right_value
0    2          c           f
1    3          d           g
2    4          e           h
3    5        NaN           i
4    6        NaN           j

In [29]:
pd.merge(left_frame, right_frame, on='key', how='outer')

key left_value right_value
0    0          a         NaN
1    1          b         NaN
2    2          c           f
3    3          d           g
4    4          e           h
5    5        NaN           i
6    6        NaN           j

In [40]:
olive.rename(columns={'Area': 'New Area'}, inplace=True)
olive

New Area  Region  Area.1  Palmitic  Palmitoleic  Stearic  Oleic  \
0      1.North-Apulia       1       1      1075           75      226   7823   
1      2.North-Apulia       1       1      1088           73      224   7709   
2      3.North-Apulia       1       1       911           54      246   8113   
3      4.North-Apulia       1       1       966           57      240   7952   
4      5.North-Apulia       1       1      1051           67      259   7771   
5      6.North-Apulia       1       1       911           49      268   7924   
6      7.North-Apulia       1       1       922           66      264   7990   
7      8.North-Apulia       1       1      1100           61      235   7728   
8      9.North-Apulia       1       1      1082           60      239   7745   
9     10.North-Apulia       1       1      1037           55      213   7944   
10    11.North-Apulia       1       1      1051           35      219   7978   
11    12.North-Apulia       1       1      1036           59      235   7868   
12    13.North-Apulia       1       1      1074           70      214   7728   
13    14.North-Apulia       1       1       875           52      243   8018   
14    15.North-Apulia       1       1       952           49      254   7795   
15    16.North-Apulia       1       1      1155           98      201   7606   
16    17.North-Apulia       1       1       943           94      183   7840   
17    18.North-Apulia       1       1      1278           69      205   7344   
18    19.North-Apulia       1       1       961           70      195   7958   
19    20.North-Apulia       1       1       952           77      258   7820   
20    21.North-Apulia       1       1      1074           67      236   7692   
21    22.North-Apulia       1       1       995           46      288   7806   
22    23.North-Apulia       1       1      1056           53      247   7703   
23    24.North-Apulia       1       1      1065           39      234   7876   
24    25.North-Apulia       1       1      1065           45      245   7779   
25        26.Calabria       1       2      1315          139      230   7299   
26        27.Calabria       1       2      1321          136      217   7174   
27        28.Calabria       1       2      1359          115      246   7234   
28        29.Calabria       1       2      1378          111      272   7127   
29        30.Calabria       1       2      1295          109      245   7253   
..                ...     ...     ...       ...          ...      ...    ...   
542  543.West-Liguria       3       8      1020          100      290   7620   
543  544.West-Liguria       3       8       970           90      220   7700   
544  545.West-Liguria       3       8      1180          130      220   7450   
545  546.West-Liguria       3       8      1060          140      240   7690   
546  547.West-Liguria       3       8       990          100      250   7630   
547  548.West-Liguria       3       8      1010           90      350   7630   
548  549.West-Liguria       3       8      1040           90      250   7780   
549  550.West-Liguria       3       8      1040           90      250   7810   
550  551.West-Liguria       3       8      1020           90      350   7620   
551  552.West-Liguria       3       8      1020           90      260   7620   
552  553.West-Liguria       3       8      1010           90      350   7610   
553  554.West-Liguria       3       8       920          110      340   7720   
554  555.West-Liguria       3       8      1030          100      250   7710   
555  556.West-Liguria       3       8       960           90      300   7820   
556  557.West-Liguria       3       8      1030          110      210   7810   
557  558.West-Liguria       3       8      1010          100      240   7710   
558  559.West-Liguria       3       8      1020           90      240   7800   
559  560.West-Liguria       3       8      1120           90      300   7650   
560  561.West

In [44]:
olive['Region'].unique()

array([1, 2, 3])

In [53]:
list(set(map(lambda x: x.split('.')[1], olive['New Area'])))

['Sicily',
 'Calabria',
 'Inland-Sardinia',
 'Coast-Sardinia',
 'West-Liguria',
 'North-Apulia',
 'East-Liguria',
 'Umbria',
 'South-Apulia']

In [50]:
olive['whoa'] = olive['Region']

In [51]:
olive

New Area  Region  Area.1  Palmitic  Palmitoleic  Stearic  Oleic  \
0      1.North-Apulia       1       1      1075           75      226   7823   
1      2.North-Apulia       1       1      1088           73      224   7709   
2      3.North-Apulia       1       1       911           54      246   8113   
3      4.North-Apulia       1       1       966           57      240   7952   
4      5.North-Apulia       1       1      1051           67      259   7771   
5      6.North-Apulia       1       1       911           49      268   7924   
6      7.North-Apulia       1       1       922           66      264   7990   
7      8.North-Apulia       1       1      1100           61      235   7728   
8      9.North-Apulia       1       1      1082           60      239   7745   
9     10.North-Apulia       1       1      1037           55      213   7944   
10    11.North-Apulia       1       1      1051           35      219   7978   
11    12.North-Apulia       1       1      1036           59      235   7868   
12    13.North-Apulia       1       1      1074           70      214   7728   
13    14.North-Apulia       1       1       875           52      243   8018   
14    15.North-Apulia       1       1       952           49      254   7795   
15    16.North-Apulia       1       1      1155           98      201   7606   
16    17.North-Apulia       1       1       943           94      183   7840   
17    18.North-Apulia       1       1      1278           69      205   7344   
18    19.North-Apulia       1       1       961           70      195   7958   
19    20.North-Apulia       1       1       952           77      258   7820   
20    21.North-Apulia       1       1      1074           67      236   7692   
21    22.North-Apulia       1       1       995           46      288   7806   
22    23.North-Apulia       1       1      1056           53      247   7703   
23    24.North-Apulia       1       1      1065           39      234   7876   
24    25.North-Apulia       1       1      1065           45      245   7779   
25        26.Calabria       1       2      1315          139      230   7299   
26        27.Calabria       1       2      1321          136      217   7174   
27        28.Calabria       1       2      1359          115      246   7234   
28        29.Calabria       1       2      1378          111      272   7127   
29        30.Calabria       1       2      1295          109      245   7253   
..                ...     ...     ...       ...          ...      ...    ...   
542  543.West-Liguria       3       8      1020          100      290   7620   
543  544.West-Liguria       3       8       970           90      220   7700   
544  545.West-Liguria       3       8      1180          130      220   7450   
545  546.West-Liguria       3       8      1060          140      240   7690   
546  547.West-Liguria       3       8       990          100      250   7630   
547  548.West-Liguria       3       8      1010           90      350   7630   
548  549.West-Liguria       3       8      1040           90      250   7780   
549  550.West-Liguria       3       8      1040           90      250   7810   
550  551.West-Liguria       3       8      1020           90      350   7620   
551  552.West-Liguria       3       8      1020           90      260   7620   
552  553.West-Liguria       3       8      1010           90      350   7610   
553  554.West-Liguria       3       8       920          110      340   7720   
554  555.West-Liguria       3       8      1030          100      250   7710   
555  556.West-Liguria       3       8       960           90      300   7820   
556  557.West-Liguria       3       8      1030          110      210   7810   
557  558.West-Liguria       3       8      1010          100      240   7710   
558  559.West-Liguria       3       8      1020           90      240   7800   
559  560.West-Liguria       3       8      1120           90      300   7650   
560  561.West

In [54]:
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])

In [59]:
A.shape

(2, 3)

In [60]:
u+v

array([ 9,  7, -4,  9])

In [61]:
4 * u

array([ 24,   8, -12,  20])

In [88]:
np.dot(u, v)

51

In [66]:
np.linalg.norm(A)

9.1104335791442992

In [67]:
A + C

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [71]:
A - C.transpose()

array([[-4, -7, -3],
       [ 3,  6,  4]])

In [72]:
C.transpose() + 3 * D

array([[14,  3,  3],
       [ 2,  7,  9]])

In [80]:
B * A.transpose()

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [85]:
np.dot(B, A.transpose())

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [89]:
np.dot(C, B)

array([[ 5, -6],
       [ 9, -8],
       [ 6, -6]])

array([[ 5, -5],
       [ 4,  5]])

In [99]:
b_squared = np.dot(B, B)

In [93]:
np.dot(b_squared, b_squared)

array([[ 1, -4],
       [ 0,  1]])

In [95]:
np.dot(A, A.transpose())

array([[14, 28],
       [28, 69]])

In [100]:
np.dot(D.transpose(), D)

array([[10, -4,  0],
       [-4,  8,  8],
       [ 0,  8, 10]])

In [104]:
np.multiply(B, B)

array([[1, 1],
       [0, 1]])

In [105]:
B*B

array([[1, 1],
       [0, 1]])